### ISSUE TITLE
extend scargo.toml [test] section posibilities

### ISSUE THREAD

**Issue by aaksenczuk** [Spyro-Soft/scargo#227]
**Is your feature request related to a problem? Please describe.**
Add the possibility in for the test to add custom make flags as it is possible for the main project.

**Describe the solution you'd like**
There should be a possibility to define profiles for test and add custom flags as it is possible for main project: eg. 
[profile.Debug]
SIMU = "ON"
SDKCONFIG = "${CMAKE_BINARY_DIR}/sdkconfig"
Those flags then will be used in main UT cmake as a set()

**Comment by jze-spyro** [comment]
There is nothing to be done, it already works like this. You can add custom cmake variables directly in the `[tests]` table in `scargo.toml`.
Personally I don't like it, because custom variables should not share a namespace with predefined ones (for example, any new predefined variable potentially breaks backwards compatibility), but I guess it's too late to change it.

**Comment by aaksenczuk** [comment]
ok, to be tested

**Comment by jze-spyro** [comment]
@aaksenczuk
has it been tested?
